### ISSUE TITLE
Publish service fails

### ISSUE THREAD

**Issue by godchaser** [godchaser/PlaySong#23]
Select all songs and publish pdf under name Test1:
```
[debug] application - Failed to publishing service
javax.persistence.PersistenceException: ERROR executing DML bindLog[101,test@test.com,test,Test1,Fri Dec 25 22:09:53 CET 2015,] error[Unique index or primary key violation: "PK_SERVICE ON PUBLIC.SERVICE(ID) VALUES ( /* 30 */ 101 )"; SQL statement:\n insert into service (id, user_email, user_name, service_name, date_created) values (?,?,?,?,?) [23505-187]]
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:90)
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.insert(DmlBeanPersister.java:57)
	at com.avaje.ebeaninternal.server.persist.DefaultPersistExecute.executeInsertBean(DefaultPersistExecute.java:59)
	at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeNow(PersistRequestBean.java:446)
	at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeOrQueue(PersistRequestBean.java:480)
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.insert(DefaultPersister.java:261)
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.insert(DefaultPersister.java:211)
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.save(DefaultPersister.java:199)
	at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1461)
	at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1454)
	at com.avaje.ebean.Model.save(Model.java:208)
	at controllers.Application.generateSongbook(Application.java:864)
	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$36$$anonfun$apply$36.apply(Routes.scala:1045)
	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$36$$anonfun$apply$36.apply(Routes.scala:1045)
	at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:136)
	at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$14$$anon$3$$anon$1.invocation(HandlerInvoker.scala:127)
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:70)
	at play.http.DefaultHttpRequestHandler$1.call(DefaultHttpRequestHandler.java:20)
	at play.core.j.JavaAction$$anonfun$7.apply(JavaAction.scala:94)
	at play.core.j.JavaAction$$anonfun$7.apply(JavaAction.scala:94)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
	at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:32)
	at scala.concurrent.impl.Future$.apply(Future.scala:31)
	at scala.concurrent.Future$.apply(Future.scala:492)
	at play.core.j.JavaAction.apply(JavaAction.scala:94)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:104)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:103)
	at scala.Option.map(Option.scala:146)
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:103)
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:96)
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:524)
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:524)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:560)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:560)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:537)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:537)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: "PK_SERVICE ON PUBLIC.SERVICE(ID) VALUES ( /* 30 */ 101 )"; SQL statement:
insert into service (id, user_email, user_name, service_name, date_created) values (?,?,?,?,?) [23505-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.index.BaseIndex.getDuplicateKeyException(BaseIndex.java:102)
	at org.h2.index.PageBtree.find(PageBtree.java:120)
	at org.h2.index.PageBtreeLeaf.addRow(PageBtreeLeaf.java:150)
	at org.h2.index.PageBtreeLeaf.addRowTry(PageBtreeLeaf.java:103)
	at org.h2.index.PageBtreeIndex.addRow(PageBtreeIndex.java:96)
	at org.h2.index.PageBtreeIndex.add(PageBtreeIndex.java:87)
	at org.h2.index.MultiVersionIndex.add(MultiVersionIndex.java:58)
	at org.h2.table.RegularTable.addRow(RegularTable.java:119)
	at org.h2.command.dml.Insert.insertRows(Insert.java:156)
	at org.h2.command.dml.Insert.update(Insert.java:114)
	at org.h2.command.CommandContainer.update(CommandContainer.java:78)
	at org.h2.command.Command.executeUpdate(Command.java:254)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:157)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:143)
	at com.zaxxer.hikari.proxy.PreparedStatementProxy.executeUpdate(PreparedStatementProxy.java:61)
	at com.zaxxer.hikari.proxy.PreparedStatementJavassistProxy.executeUpdate(PreparedStatementJavassistProxy.java)
	at com.avaje.ebeaninternal.server.type.DataBind.executeUpdate(DataBind.java:56)
	at com.avaje.ebeaninternal.server.persist.dml.InsertHandler.execute(InsertHandler.java:128)
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:80)
	... 49 more
[debug] application - hash [25-12-2015_100950]
```

**Comment by godchaser** [comment]
ebean update seems to fix this
