### ISSUE TITLE
Adding new songs sometimes fail

### ISSUE THREAD

**Issue by godchaser** [godchaser/PlaySong#24]
```
[debug] application - Checking song lines: A1
[trace] application - Checking chords A1
[trace] application - Song key:A
[trace] o.a.ebean.SQL - txn[1023] insert into song (id, song_name, song_original_title, song_author, song_link, song_importer, song_last_modified_by, song_book_id, date_created, date_modified) values (?,?,?,?,?,?,?,?,?,?); --bind(461,BBbbb,,,,null,test,0,Sat Dec 26 23:25:47 CET 2015,Sat Dec 26 23:25:47 CET 2015,)
[error] p.c.s.n.PlayDefaultUpstreamHandler - Cannot invoke the action
javax.persistence.PersistenceException: ERROR executing DML bindLog[461,BBbbb,,,,null,test,0,Sat Dec 26 23:25:47 CET 2015,Sat Dec 26 23:25:47 CET 2015,] error[Unique index or primary key violation: "PK_SONG ON PUBLIC.SONG(ID) VALUES ( /* 298 */ 461 )"; SQL statement:\n insert into song (id, song_name, song_original_title, song_author, song_link, song_importer, song_last_modified_by, song_book_id, date_created, date_modified) values (?,?,?,?,?,?,?,?,?,?) [23505-187]]
    at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:90) ~[avaje-ebeanorm-4.6.2.jar:na]
    at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.insert(DmlBeanPersister.java:57) ~[avaje-ebeanorm-4.6.2.jar:na]
    at com.avaje.ebeaninternal.server.persist.DefaultPersistExecute.executeInsertBean(DefaultPersistExecute.java:59) ~[avaje-ebeanorm-4.6.2.jar:na]
    at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeNow(PersistRequestBean.java:446) ~[avaje-ebeanorm-4.6.2.jar:na]
    at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeOrQueue(PersistRequestBean.java:480) ~[avaje-ebeanorm-4.6.2.jar:na]
    at com.avaje.ebeaninternal.server.persist.DefaultPersister.insert(DefaultPersister.java:261) ~[avaje-ebeanorm-4.6.2.jar:na]
    at com.avaje.ebeaninternal.server.persist.DefaultPersister.insert(DefaultPersister.java:211) ~[avaje-ebeanorm-4.6.2.jar:na]
    at com.avaje.ebeaninternal.server.persist.DefaultPersister.save(DefaultPersister.java:199) ~[avaje-ebeanorm-4.6.2.jar:na]
    at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1461) ~[avaje-ebeanorm-4.6.2.jar:na]
    at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1454) ~[avaje-ebeanorm-4.6.2.jar:na]
Caused by: org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: "PK_SONG ON PUBLIC.SONG(ID) VALUES ( /* 298 */ 461 )"; SQL statement:
insert into song (id, song_name, song_original_title, song_author, song_link, song_importer, song_last_modified_by, song_book_id, date_created, date_modified) values (?,?,?,?,?,?,?,?,?,?) [23505-187]
    at org.h2.engine.SessionRemote.done(SessionRemote.java:622) ~[h2-1.4.187.jar:1.4.187]
    at org.h2.command.CommandRemote.executeUpdate(CommandRemote.java:191) ~[h2-1.4.187.jar:1.4.187]
    at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:157) ~[h2-1.4.187.jar:1.4.187]
    at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:143) ~[h2-1.4.187.jar:1.4.187]
    at com.zaxxer.hikari.proxy.PreparedStatementProxy.executeUpdate(PreparedStatementProxy.java:61) ~[HikariCP-2.3.7.jar:na]
    at com.zaxxer.hikari.proxy.PreparedStatementJavassistProxy.executeUpdate(PreparedStatementJavassistProxy.java) ~[HikariCP-2.3.7.jar:na]
    at com.avaje.ebeaninternal.server.type.DataBind.executeUpdate(DataBind.java:56) ~[avaje-ebeanorm-4.6.2.jar:na]
    at com.avaje.ebeaninternal.server.persist.dml.InsertHandler.execute(InsertHandler.java:128) ~[avaje-ebeanorm-4.6.2.jar:na]
    at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:80) ~[avaje-ebeanorm-4.6.2.jar:na]
    at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.insert(DmlBeanPersister.java:57) ~[avaje-ebeanorm-4.6.2.jar:na]
[error] application - 

! @6ohg2impe - Internal server error, for (POST) [/songs] ->

play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[PersistenceException: ERROR executing DML bindLog[461,BBbbb,,,,null,test,0,Sat Dec 26 23:25:47 CET 2015,Sat Dec 26 23:25:47 CET 2015,] error[Unique index or primary key violation: "PK_SONG ON PUBLIC.SONG(ID) VALUES ( /* 298 */ 461 )"; SQL statement:\n insert into song (id, song_name, song_original_title, song_author, song_link, song_importer, song_last_modified_by, song_book_id, date_created, date_modified) values (?,?,?,?,?,?,?,?,?,?) [23505-187]]]]
    at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:265) ~[play_2.11-2.4.6.jar:2.4.6]
    at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[play_2.11-2.4.6.jar:2.4.6]
    at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [play_2.11-2.4.6.jar:2.4.6]
    at play.core.j.JavaGlobalSettingsAdapter.play$core$j$JavaGlobalSettingsAdapter$$super$onError(JavaGlobalSettingsAdapter.scala:36) [play_2.11-2.4.6.jar:2.4.6]
    at play.core.j.JavaGlobalSettingsAdapter$$anonfun$onError$2.apply(JavaGlobalSettingsAdapter.scala:36) [play_2.11-2.4.6.jar:2.4.6]
    at play.core.j.JavaGlobalSettingsAdapter$$anonfun$onError$2.apply(JavaGlobalSettingsAdapter.scala:36) [play_2.11-2.4.6.jar:2.4.6]
    at scala.Option.getOrElse(Option.scala:121) [scala-library-2.11.7.jar:na]
    at play.core.j.JavaGlobalSettingsAdapter.onError(JavaGlobalSettingsAdapter.scala:36) [play_2.11-2.4.6.jar:2.4.6]
    at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94) [play_2.11-2.4.6.jar:2.4.6]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:266) [play-netty-server_2.11-2.4.6.jar:2.4.6]
Caused by: javax.persistence.PersistenceException: ERROR executing DML bindLog[461,BBbbb,,,,null,test,0,Sat Dec 26 23:25:47 CET 2015,Sat Dec 26 23:25:47 CET 2015,] error[Unique index or primary key violation: "PK_SONG ON PUBLIC.SONG(ID) VALUES ( /* 298 */ 461 )"; SQL statement:\n insert into song (id, song_name, song_original_title, song_author, song_link, song_importer, song_last_modified_by, song_book_id, date_created, date_modified) values (?,?,?,?,?,?,?,?,?,?) [23505-187]]
    at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:90) ~[avaje-ebeanorm-4.6.2.jar:na]
    at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.insert(DmlBeanPersister.java:57) ~[avaje-ebeanorm-4.6.2.jar:na]
    at com.avaje.ebeaninternal.server.persist.DefaultPersistExecute.executeInsertBean(DefaultPersistExecute.java:59) ~[avaje-ebeanorm-4.6.2.jar:na]
    at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeNow(PersistRequestBean.java:446) ~[avaje-ebeanorm-4.6.2.jar:na]
    at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeOrQueue(PersistRequestBean.java:480) ~[avaje-ebeanorm-4.6.2.jar:na]
    at com.avaje.ebeaninternal.server.persist.DefaultPersister.insert(DefaultPersister.java:261) ~[avaje-ebeanorm-4.6.2.jar:na]
    at com.avaje.ebeaninternal.server.persist.DefaultPersister.insert(DefaultPersister.java:211) ~[avaje-ebeanorm-4.6.2.jar:na]
    at com.avaje.ebeaninternal.server.persist.DefaultPersister.save(DefaultPersister.java:199) ~[avaje-ebeanorm-4.6.2.jar:na]
    at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1461) ~[avaje-ebeanorm-4.6.2.jar:na]
    at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1454) ~[avaje-ebeanorm-4.6.2.jar:na]
Caused by: org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: "PK_SONG ON PUBLIC.SONG(ID) VALUES ( /* 298 */ 461 )"; SQL statement:
insert into song (id, song_name, song_original_title, song_author, song_link, song_importer, song_last_modified_by, song_book_id, date_created, date_modified) values (?,?,?,?,?,?,?,?,?,?) [23505-187]
    at org.h2.engine.SessionRemote.done(SessionRemote.java:622) ~[h2-1.4.187.jar:1.4.187]
    at org.h2.command.CommandRemote.executeUpdate(CommandRemote.java:191) ~[h2-1.4.187.jar:1.4.187]
    at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:157) ~[h2-1.4.187.jar:1.4.187]
    at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:143) ~[h2-1.4.187.jar:1.4.187]
    at com.zaxxer.hikari.proxy.PreparedStatementProxy.executeUpdate(PreparedStatementProxy.java:61) ~[HikariCP-2.3.7.jar:na]
    at com.zaxxer.hikari.proxy.PreparedStatementJavassistProxy.executeUpdate(PreparedStatementJavassistProxy.java) ~[HikariCP-2.3.7.jar:na]
    at com.avaje.ebeaninternal.server.type.DataBind.executeUpdate(DataBind.java:56) ~[avaje-ebeanorm-4.6.2.jar:na]
    at com.avaje.ebeaninternal.server.persist.dml.InsertHandler.execute(InsertHandler.java:128) ~[avaje-ebeanorm-4.6.2.jar:na]
    at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:80) ~[avaje-ebeanorm-4.6.2.jar:na]
    at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.insert(DmlBeanPersister.java:57) ~[avaje-ebeanorm-4.6.2.jar:na]
[debug] application - Secured: redirect URL: /songs
```

**Comment by godchaser** [comment]
Not happening anymore, seems that ebean update fixed this
